// Hand-written fixtures. Everything in this file was typed out by hand — board drawings,
// clue numbers and expected solutions — and nothing here is imported from the code under
// test, because a fixture generated by the thing it tests proves nothing. The tests that
// read this file check the programs against a picture a person can verify.
//
// ACID TEST 1 — a unique 4x4 board, fleet [2,1].
//
//   # . . .
//   # . . .
//   . . . .
//   . . # .
//
//   row clues 1 1 0 1   (sum 3)
//   col clues 2 0 1 0   (sum 3)   fleet 2 + 1 = 3   -> the identity holds
//
// Why it has exactly one solution, argued by hand:
//   * every row holds at most one occupied cell, so the 2-cell ship cannot lie along a row
//     -> it is vertical, in some column
//   * the only column asking for two cells is column 0 -> the ship is (0,0)-(1,0)
//     (rows 1-2 and 2-3 are impossible because row 2's clue is 0)
//   * column 2 asks for one cell. Rows 0 and 1 already have theirs, row 2 is empty by its
//     clue, so the 1-cell ship is at (3,2)
//   * check the Akaji rule: (3,2) is two rows below (1,x), so no touch, corner included
//
// The reasoning solver should not need a single guess on this board: depth 0.
export const UNIQUE_4x4 = {
  name: 'unique 4x4, fleet [2,1]',
  drawing: [
    '#...',
    '#...',
    '....',
    '..#.',
  ],
  spec: {
    rows: 4,
    cols: 4,
    fleet: [2, 1],
    rowReq: [1, 1, 0, 1],
    colReq: [2, 0, 1, 0],
  },
  solution: [
    { r: 0, c: 0, len: 2, axis: 'v' },
    { r: 3, c: 2, len: 1, axis: 'h' },
  ],
  depth: 0,
};

// ACID TEST 2 — the same fleet on a board with two answers, so the counter has to return 2
// and not one of them by preference.
//
//   . # . .
//   . . . .
//   . . . .
//   . . # #
//
//   row clues 1 0 0 2   (sum 3)
//   col clues 0 1 1 1   (sum 3)
//
//   Row 3 holds two adjacent cells, so it is the 2-ship: either (3,1)-(3,2) or (3,2)-(3,3).
//   In the first case the lone cell left in column 3 must be the 1-ship at (0,3) — but then
//   (0,3) touches nothing, fine — and in the second case column 1's cell is the 1-ship at
//   (0,1). Both boards satisfy every clue and neither has a touch: exactly two solutions.
export const AMBIGUOUS_4x4 = {
  name: 'ambiguous 4x4, fleet [2,1]',
  drawing: [
    '.#..',
    '....',
    '....',
    '..##',
  ],
  spec: {
    rows: 4,
    cols: 4,
    fleet: [2, 1],
    rowReq: [1, 0, 0, 2],
    colReq: [0, 1, 1, 1],
  },
  solutions: [
    [
      { r: 3, c: 1, len: 2, axis: 'h' },
      { r: 0, c: 3, len: 1, axis: 'h' },
    ],
    [
      { r: 3, c: 2, len: 2, axis: 'h' },
      { r: 0, c: 1, len: 1, axis: 'h' },
    ],
  ],
};

// ACID TEST 3 — a spec whose clues add up and that still has no answer at all: column 1
// demands three stacked cells and the fleet has no ship that long.
//
//   . # . .        the only column with a clue above 1 is column 1, and it wants 3
//   . # . .        rows 0,1,2 would have to be one ship of length 3 — the fleet is [2,1]
//   . # . .
//   . . . .
export const IMPOSSIBLE_4x4 = {
  name: 'impossible 4x4, fleet [2,1]',
  spec: {
    rows: 4,
    cols: 4,
    fleet: [2, 1],
    rowReq: [1, 1, 1, 0],
    colReq: [0, 3, 0, 0],
  },
};

// Specs that fail the counting identity. Each one is rejected by the checker before any
// searching happens, with Σ(row) != Σ(col) or Σ != Σ(fleet) as the reason.
export const BROKEN_SPECS = [
  { why: 'rows and columns disagree', spec: { rows: 4, cols: 4, fleet: [2, 1], rowReq: [1, 1, 0, 1], colReq: [2, 0, 1, 1] } },
  { why: 'columns do not match the fleet', spec: { rows: 4, cols: 4, fleet: [2, 2], rowReq: [1, 1, 1, 1], colReq: [2, 0, 1, 0] } },
  { why: 'both axes agree with each other but not with the fleet', spec: { rows: 3, cols: 3, fleet: [3], rowReq: [1, 1, 2], colReq: [1, 1, 2] } },
  { why: 'a fleet of one, clues of two', spec: { rows: 4, cols: 4, fleet: [4], rowReq: [2, 2, 0, 0], colReq: [1, 1, 1, 0] } },
];
